controller_manager:
  ros__parameters:
  # change from 30 to 100
    update_rate: 100
    # use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_footprint

    left_wheel_names: ['wheel_FL_joint','wheel_RL_joint']
    right_wheel_names: ['wheel_FR_joint','wheel_RR_joint']

    # <!-- wheel separation according to urdf 0.08214+0.14167=0.22381-->
    # measure using ruler center of wheel to center of wheel 0.358
    # take from leorover github = 0.33
    wheel_separation: 0.33

    #  <!-- dont know if its 0.057 or 0.0625 radius here took 0.057 -->
    # using ruler it matches 0.0625
    wheel_radius: 0.0625

    use_stamped_vel: false

    open_loop: false   

    wheels_per_side: 2
    wheel_separation_multiplier: 2.5
    # left_wheel_radius_multiplier: x
    # right_wheel_radius_multiplier: x

    # odom_frame_id: x
    # pose_covariance_diagonal: x
    # twist_covariance_diagonal: x
    # open_loop: x
    # enable_odom_tf: x

    # cmd_vel_timeout: x
    # publish_limited_velocity: x
    # velocity_rolling_window_size: x
    

    # linear.x.has_velocity_limits: false
    # linear.x.has_acceleration_limits: false
    # linear.x.has_jerk_limits: false
    # linear.x.max_velocity: NAN
    # linear.x.min_velocity: NAN
    # linear.x.max_acceleration: NAN
    # linear.x.min_acceleration: NAN
    # linear.x.max_jerk: NAN
    # linear.x.min_jerk: NAN

    # angular.z.has_velocity_limits: false
    # angular.z.has_acceleration_limits: false
    # angular.z.has_jerk_limits: false
    # angular.z.max_velocity: NAN
    # angular.z.min_velocity: NAN
    # angular.z.max_acceleration: NAN
    # angular.z.min_acceleration: NAN
    # angular.z.max_jerk: NAN
    # angular.z.min_jerk: NAN




# joint_broad:
#   ros__parameters: